FROM python:3.10-slim

LABEL maintainer="msh36345@gmail.com"
LABEL description="run naive bayes v2 client"

WORKDIR /app

COPY Main-client.py .
COPY Manager-client.py .
COPY Server-client.py .
COPY titanic.csv .
COPY Trainer.py .
COPY Validator.py .

COPY requirements-client.txt .
RUN pip install --no-cache-dir -r requirements-client.txt

EXPOSE 8090


CMD ["uvicorn", "Server-client:app", "--host", "0.0.0.0", "--port", "8090"]