FROM python:3.10-slim

LABEL maintainer="msh36345@gmail.com"
LABEL description="run naive bayes v2 host"

WORKDIR /app

COPY Classifier.py .
COPY Cleaner.py .
COPY Loader.py .
COPY Log.py .
COPY Main-host.py .
COPY Manager-host.py .
COPY Server-host.py .
COPY titanic.csv .
COPY Trainer.py .
COPY Validator.py .

COPY requirements-host.txt .
RUN pip install --no-cache-dir -r requirements-host.txt

EXPOSE 8070


CMD ["uvicorn", "Server-host:app", "--host", "0.0.0.0", "--port", "8070"]